# Generated by Django 4.0.3 on 2022-05-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GstBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceno', models.CharField(max_length=12)),
                ('invoicedate', models.CharField(max_length=12)),
                ('gstno', models.CharField(max_length=12)),
                ('sgst', models.CharField(max_length=12)),
                ('cgst', models.CharField(max_length=12)),
                ('igst', models.CharField(max_length=12)),
                ('total_amount', models.CharField(max_length=18)),
            ],
        ),
    ]
